use curl upload rather than github action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,16 +62,23 @@ jobs:
         asset_name: ${{steps.init.outputs.tag_name}}.zip
         asset_content_type: application/zip
 
-    - name: Upload zip to CurseForge
-      id: curseforgeUpload
-      uses: fjogeleit/http-request-action@master
-      with:
-        url: 'https://wow.curseforge.com/api/projects/${{ env.CURSEFORGE_PROJECT_ID }}/upload-file'
-        method: 'POST'
-        data: '{ "metadata": "{ \"changelog\": \"${{github.event.inputs.version}}\", \"displayName\": \"${{ steps.init.outputs.tag_name }}.zip\", \"gameVersions\": [8290], \"releaseType\": \"release\" }"}'
-        files: '{ "file": ".releases/${{ steps.init.outputs.tag_name }}.zip" }'
-        customHeaders: '{ "X-Api-Token": "${{ secrets.CURSEFORGE_API_TOKEN }}" }'
+    # - name: Upload zip to CurseForge
+    #   id: curseforgeUpload
+    #   uses: fjogeleit/http-request-action@master
+    #   with:
+    #     url: 'https://wow.curseforge.com/api/projects/${{ env.CURSEFORGE_PROJECT_ID }}/upload-file'
+    #     method: 'POST'
+    #     data: '{ "metadata": "{ \"changelog\": \"${{github.event.inputs.version}}\", \"displayName\": \"${{ steps.init.outputs.tag_name }}.zip\", \"gameVersions\": [8290], \"releaseType\": \"release\" }"}'
+    #     files: '{ "file": ".releases/${{ steps.init.outputs.tag_name }}.zip" }'
+    #     customHeaders: '{ "X-Api-Token": "${{ secrets.CURSEFORGE_API_TOKEN }}" }'
 
-    - name: Show Response
-      run: echo ${{ steps.curseforgeUpload.outputs.response }}
-      if: success() || failure()
+    # - name: Show Response
+    #   run: echo ${{ steps.curseforgeUpload.outputs.response }}
+    #   if: success() || failure()
+
+    - name: Upload zip to CurseForge
+      run: |
+        curl -s https://wow.curseforge.com/api/projects/${{ env.CURSEFORGE_PROJECT_ID }}/upload-file \
+          -H 'X-Api-Token: ${{ secrets.CURSEFORGE_API_TOKEN }}' \
+          -F file=@.releases/${{ steps.init.outputs.tag_name }}.zip \
+          -F metadata='{ "changelog": "${{github.event.inputs.version}}", "displayName": "${{ steps.init.outputs.tag_name }}.zip", "gameVersions": [8290], "releaseType": "release"}'
